source $HOME/.config/nvim/plugins/plugin.vim
source $HOME/.config/nvim/settings/airlines.vim
source $HOME/.config/nvim/settings/cp.vim
source $HOME/.config/nvim/settings/py.vim
source $HOME/.config/nvim/settings/verilog.vim
source $HOME/.config/nvim/settings/tree.vim
source $HOME/.config/nvim/settings/keymaps.vim
source $HOME/.config/nvim/settings/setting.vim
source $HOME/.config/nvim/settings/cocsetting.vim
source $HOME/.config/nvim/settings/jsreact.vim
